# Site settings
title: The Spring Peaks
description: >- # this means to ignore newlines until "baseurl:"
  The Spring Peaks are a five piece rock band from Perth, Western Australia.
  Jake Ostle (vocals, guitar),
  Brad Shaw (guitar),
  Jerram Gibson (keys),
  Lucas Biral (bass),
  Daniel Cavalli (drums).
url: 'https://defce74.github.io/'
baseurl: '/thespringpeaks'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'The Spring Peaks'
  email: thespringpeaks@gmail.com
  facebook_username: thespringpeaks
  github_username:  defce74
  instagram_username:  thespringpeaks_
  spotify_username: thespringpeaks

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:title
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
